### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by keirog**
❤ (also, apologies for that line-break change—GitHub did it)

### CODE REVIEW

**Comment by chee** [comment]
i also approve of the introduction of the trailing newline

**Comment by notlee** [comment]
This is a copy-pasta component files used for testing, the real typo is here! 
https://github.com/Financial-Times/o-forms/pull/305

**Comment by keirog** [comment]
Ohhh, oops, thanks both!

**Comment by keirog** [comment]
~line break~ newline
Honestly today, what a day

**Pull request merged**
