### PR TITLE
MAJOR: Remove commonjs transform and keep component code as esm

### PR DESCRIPTION
**Pull request by JakeChampion**
Fixes https://github.com/Financial-Times/origami-component-converter/issues/31

### CODE REVIEW

**Comment by JakeChampion** [comment]
The babel compiler has been configured to compile down to a syntax which all browsers who support esm will support. Because of that, I don't think this is a breaking change as we haven't changed the target browser support at all.

**Comment by chee** [comment]
If it turns out to break anything, do we have a backup plan?

I think it looks like:
* Revert the change
* Release a new version of OCC
* Release a patch to every component that was released since this change went in

**Comment by chee** [comment]
If it turns out to break anything, do we have a backup plan?

I think it looks like:
* Revert the change
* Release a new version of OCC
* Release a patch to every component that was released since this change went in

**Comment by chee** [comment]
p.s. this looks great, i'm excited :)))

**Pull request merged**
