### PR TITLE
automate publishing to npm

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
We tried to version this automatically but we failed. Please view the errors at https://github.com/Financial-Times/origami-component-converter/runs/272488825?check_suite_focus=true

**Comment by JakeChampion** [comment]
The real link for the failed job is https://github.com/Financial-Times/origami-component-converter/runs/1166062422?check_suite_focus=true

**Comment by JakeChampion** [comment]
I think this issue stems from the repo originally being made under chee/origami-component-converter and then was moved to financial-times/origami-component-converter

**Comment by JakeChampion** [comment]
Reported this issue to GitHub because we can not create a release via the API in any form:
- Using the current org/repo name -- https://api.github.com/repos/Financial-times/origami-component-converter/releases
- Using the old org/repo name -- https://api.github.com/repos/chee/origami-component-converter/releases
- Using the repo ID -- https://api.github.com/repositories/156867479/releases

**Pull request merged**
